name: Manual Webhook Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-curl-put:
    runs-on: ubuntu-latest
    
    env:
      BATCH_URL: "https://webhook.site/72b85988-b484-4895-bb61-33a66d9d57bc"

    steps:
      - name: Create Test File
        run: |
          cat <<EOF > testfile.txt
          anjffss                 34634637                ss9d8s7wq7
          sdsdsd                34634637                ss9d8s7wq7
          anjsssf                34634637                ss9d8s7wq7
          EOF

      - name: Run Fixed Curl Command
        run: |
          curl -v -k --location \
            --request PUT "$BATCH_URL" \
            -H 'Content-Type: multipart/form-data; boundary=----------2363276482382293722938270018'  \
            --form 'filename=TEST_FILE_NAME' \
            --form 'type=TEST_FILE_TYPE' \
            --form 'artifactFile=@"testfile.txt"'
