name: Generate CSV and Show It

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run tempscript.py to generate CSV
        run: python .github/workflows/tempscript.py

      - name: Display contents of generated CSV
        run: cat sample.csv
