name: Run Python Script

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create temp.json
        run: echo "{ \"Name\": \"AK\" }" > temp.json

      - name: Install dependencies (optional)
        run: |
          pip install -r requirements.txt || true

      - name: Run tempscript.py
        run: python tempscript.py
