name: Generate CSV and Show It

on:
  schedule:
    - cron: '45 16 * * *'

jobs:
  run-script:
    if: |
      github.event_name != 'schedule' || 
      github.ref == 'refs/heads/main' || 
      github.ref == 'refs/heads/test1' || 
      github.ref == 'refs/heads/test2'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Say hello from branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Hello from $BRANCH_NAME"

      - name: Run tempscript.py to generate CSV
        run: python .github/workflows/tempscript.py

      - name: Display contents of generated CSV
        run: cat sample.csv