name: Generate CSV and Show It

on:
  workflow_dispatch:
  schedule:
    - cron: '45 16 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: test2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Say hello from checked-out branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Hello from $BRANCH_NAME"

      - name: Run tempscript.py to generate CSV
        run: python .github/workflows/tempscript.py

      - name: Display contents of generated CSV
        run: cat sample.csv
