name: Run Python Script

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # You can change the version if needed

      - name: Install dependencies (optional)
        run: |
          pip install -r requirements.txt || true  # Skip if no requirements.txt

      - name: Run script.py
        run: python tempscript.py
