name: TEMP SHARED WF

on:
  workflow_call:

jobs:
  print-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Say hello from branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Hello from $BRANCH_NAME"
          cat testfile.txt