name: TEMP SHARED WF

on:
  workflow_call:
    inputs:
      branch_name: 
        description: "Name of calling branch"
        required: true
        type: string

jobs:
  print-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Say hello from branch
        run: |
          BRANCH_NAME=${{ inputs.branch_name }}
          echo "Hello from $BRANCH_NAME"
          cat testfile.txt