name: TEMP SHARED WF

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string

jobs:
  print-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Say hello from branch
        run: |
          cat ${{ inputs.file-path }}